### ISSUE TITLE
Taxonomy endpoint

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#12]
to get taxonomic data only,

**Comment by sckott** [comment]
we may want to do this join to create a new table beforehand, and not on each call to this route, would need to do this on each time the DB is updated

**Comment by cboettig** [comment]
My current solution is to query this without a species or genus, which returns the entire joined table.  The results of this query are cached by R the first time this is called, and there-after loaded from cache; so a given session shouldn't hit the endpoint too often.  

The cached solution is handy in any event, because most other endpoints other than `/species` need a SpecCode instead of a species name.  Having this cached means I can quickly extract all the SpecCodes from the cached table without hitting the API at all. (vs having to hit /species for every species in the list!). So that's a big labor-saver on the API. 

Having the full table cached in this way is also convenient, as it seems the most common entry-point into rfishbase is to first generate a species list from some relevant higher taxonomic group.  So I've written the R functions to work in this way, e.g.

``` r
# List all species in Labrid family
labrids <- sci_names(list(Family="Labridae"))

# get a table of locations by species
locations(labrids)

# get table of summary characteristics by species 
species_table(labrids)
```

so for now I'm happy to close this.

**Comment by sckott** [comment]
okay, sounds good

ps. once we have caching, this shouldn't be such a big deal as with two requests that are the same, the 2nd and all following should just serve from the key-value store

**Comment by cboettig** [comment]
Right, but the table isn't tiny and some connections may be slow, so for a call that we might hit for every species in the list it still makes sense to do this locally I think.  But caching will definitely help on the server-side, particularly if the server gets multiple requests at the same time.

**Comment by sckott** [comment]
sounds good
