### ISSUE TITLE
Fishbase license/copyright

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#124]
- [ ] copy/paste their copyright and/or license info on the fishbaseapi docs - and in R pkg docs
- [ ] Rainer says they expect commercial users to pay a modest fee - asking about how we can help make sure that happens
- [ ] should it be returned in a field in the API responses?

cc @cboettig

**Comment by cboettig** [comment]
Good questions.  Have you seen any other APIs that have similar issues?  How do they address this?

I'm guessing it doesn't make sense to make that a field for every API response (since API responses are generally meant to be read by computers not people; this would seem to add clutter without really making these terms any more visible), though maybe there should be a dedicated API endpoint to display these terms of use.

**Comment by sckott** [comment]
I imagine most APIs would do this through API keys - that way they can vary rate limits for different tyeps of users. 

Right, agree doesn't make sense to return terms in the API response - also agree could do a separate route for that.

**Comment by cboettig** [comment]
right, though I don't suppose FishBase expects us to switch to a full-blown registration model where we verify commercial vs educational/research use and give out API keys?  Fishbase license is basically CC-BY-NC right, so commercial use is not covered by that license and would be subject to a charge of copyright infringement?  Then presumably it is sufficient from our end to just make it clear that any (re-)use is subject to the CC-BY-NC terms (unless FishBase grants the user special permission otherwise, e.g. by paying a commercial use fee)?

**Comment by sckott** [comment]
> though I don't suppose FishBase expects us to switch to a full-blown registration model where we verify commercial vs educational/research use and give out API keys?

I don't know, have asked them that - will loop you in on the email. 

> Then presumably it is sufficient from our end to just make it clear that any (re-)use is subject to the CC-BY-NC terms (unless FishBase grants the user special permission otherwise, e.g. by paying a commercial use fee)?

Seems reasonable. I've asked for details of how we should direct commercial users

**Comment by sckott** [comment]
Rainer says to "ask commercial users to contact FishBase, e.g. through the "Comments & corrections" link at the bottom of the FishBase search page."

this link: http://www.fishbase.us/mail/MailForm.php

**Comment by cboettig** [comment]
Nice, that looks like a perfectly good system.  We should just make it clear that Fishbase API is free for non-commercial use with attribution as defined by the terms of CC-BY-NC license, an that commercial users should first inquire at that address.  I imagine most commercial users would rather  get permission than open themselves up to liability for copyright infringement, and we don't have to deal with tracking API keys and registration.

**Comment by sckott** [comment]
Will do, and will open an issue in rfishbase repo to add to docs there

**Comment by sckott** [comment]
added info to the landing pages for the API - restarting API
