### ISSUE TITLE
Docker script

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#20]
@cboettig on trying to set this up on a DO droplet, lines in `docker.sh` work great, but then on trying these lines https://github.com/ropensci/fishbaseapi/blob/master/docker.sh#L22-L31 I get `FATA[0000] cannot enable tty mode on non tty input` 

I did `scp` the sql database into the droplet, so it's there and named correctly. I'm probably missing something easy...

**Comment by cboettig** [comment]
Shoot, sorry I hadn't tested that part of the script since I had it set up already.  Let's do it in steps instead, should at least be easier to debug:

Make sure the fbmysql container is running (first few lines of that script), and then can you try instead: 

``` bash
docker run --rm -ti --link fbmysql:mysql \
    -v ${PWD}/fbapp.sql:/data/fbapp.sql \
    -w /data mysql bash
```

This should drop you into a bash sell on the container, at the working directory `/data` where you should see fbapp.sql.  From the bash prompt, launch mysql:

``` bash
mysql  --host=$MYSQL_PORT_3306_TCP_ADDR \
    --protocol=$MYSQL_PORT_3306_TCP_PROTO \
    --password=$MYSQL_ENV_MYSQL_ROOT_PASSWORD 
```

That should start mysql.  And now try to import the database; e.g.

``` mysql
fbapp < fbapp.sql
```

or just `source fbapp.sql`

**Comment by sckott** [comment]
@cboettig thanks, trying that

**Comment by sckott** [comment]
cool, that worked, just need to fix one small thing https://github.com/ropensci/fishbaseapi/commit/725ded37753b1946dde1330e70110496fc846e0e#commitcomment-9688130

Should we break these up in the docker file `docker.sh` ?

**Comment by sckott** [comment]
@cboettig tested out the docker install and all things work, very nice

**Comment by cboettig** [comment]
Very cool.

I've noticed I've had some issues with the mysql container crashing on my
server (seemingly after inactivity rather than being hit hard), but I
cannot replicate locally so this might be a memory issue.  Let me know what
you see.  I've also noticed that if I just restart the mysql container with
docker restart, this doesn't seem to restablish the connection; I have to
bring the sinatra container down and restart it as well to reconnect.  I
guess the ruby command to connect isn't rerun if the connection is
completely lost,  Anyway, guess we monitor and see.

**Comment by sckott** [comment]
Okay, will keep an eye out for that in testing

**Comment by sckott** [comment]
@cboettig okay, i think we're getting close, but its not fully automated yet. do you think you could try it out on a server?  I just ran from the `docker.sh` file manually. i imagine dockerfile needs more things for it to work? 

even when it was running it seemed like I couldn't get to the log files in eleasticsearch, and it seemed that logging wasn't actually happening, but i'm not sure quite how to fix that :(

**Comment by cboettig** [comment]
sure I can take a look, not quite sure what I'm testing though.

I did figure out why the script failed before on the import mysql step and
pushed a change to master so that doesn't have to be done manually.

took a look at logging branch and pushed a few quick edits to docker.sh on
that branch too.

will try and run on the server soon

**Comment by sckott** [comment]
@cboettig sorry for not being clearer. 
1. I was hoping you could see what needs to be added to the `Dockerfile` to get this working from a simple `docker pull ropensci/fishbaseapi` 
2. and if you have any insight on might be wrong with the logstash part, doesn't seem to be working

**Comment by cboettig** [comment]
oh right, sorry. checking now

**Comment by cboettig** [comment]
Okay, I think this is all fixed in the current docker.sh, so closing.
