### ISSUE TITLE
Redis thoughts

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#21]
- We may at various points need to flush the redis cache, etc. so need to look into how to make this easy since it's running in a docker container 
- We may want to set an expiration time for caching in redis, e.g., items are only cached for 24 hrs, or 1 week?  or no expiration?

**Comment by sckott** [comment]
For flushing, simply send a `flushall` command inside the `redis-cli` command line interface

**Comment by cboettig** [comment]
Perfect.  If I do:

```
docker exec -ti fbredis bash
redis-cli flushall
```

That clears the redis cache.  At the moment caching seems broken (on unicorn branch).  Any time I repeat a call, I get an error on the second call. If I flush cache and try again, it's okay.

**Comment by sckott** [comment]
weird, okay, will look into this

**Comment by sckott** [comment]
@cboettig Any reason to set an expiry date/time for cached responses?  Or keep them indefinitely?  Or to whenever the DB is updated (hard to automate perhaps)?

**Comment by cboettig** [comment]
I don't think so.  At the moment the redis cache isn't being written to the host, so it's only a permanent as the redis container.  You don't lose the data if the redis container goes down (e.g. enters a `stopped` state, since `docker start fbredis` will bring it back up) but if the container is removed then the cache is lost.  This seems fine to me, but we could make it permanent.  There's also the various redis backup mechanisms, but I don't think we need those either since it's just cache data.  

For the moment manually purging the cache when the DB is upgraded seems fine to me.  In between times I think we'll just need to be monitoring a bit on all the components to get a sense of performance, but I think mysql is more likely to be the weak point.

**Comment by sckott** [comment]
Okay, sounds good, closing this
