### ISSUE TITLE
Check parameters

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#27]
Some routes will fail when a parameter is passed that is not a field in the table being queried. Right now we use `check_fields()` to make sure the user isn't requesting a field that doesn't exist, but we should do similarly for fields queried on.

**Comment by sckott** [comment]
two options:
- could throw error if a field does not exist in the table, and stop request, 
- or drop silently

seems that many apis we work with use the latter approach, GBIF, PLOS ALM, etc.

**Comment by cboettig** [comment]
Yeah, the latter seems fine

**Comment by sckott** [comment]
@cboettig curious about your thoughts on case. 

For trying to silently drop parameters that don't exist, what if there is a case mismatch?  That is, most fields in the tables in the fishbase DB are camelcase (i think?) and so if user passes `genus` and the field name in the DB is `Genus`, then we don't want to drop that parameter, do we? I imagine we want to do the parameter checking by lowercasing all user parameters, lowercase all table fields, then do the match. But since table fields are still camelcase, if user gives `genus`, we need to convert that to `Genus` before sending the query to the DB. The benefit of all lowercase is users not having to remember case. OR, do we just match case used in the DB and drop those params that don't match, even if it's just a case mismatch?

**Comment by cboettig** [comment]
Are REST URLs case sensitive then?  I keep getting confused as to
when/whether http URLs are case insensitive.  Anyway, I agree it makes
sense that we handle them in a case insensitive way, so that a user can use
Genus or genus.

That said, I think it's worth bearing in mind that there really isn't any
documentation of the fields of the SQL database anyway, so I imagine a user
would have no idea what fields are available unless they've first made a
query to return all fields.  For a case like the rfishbase client, we will
mostly handle fields for them, in most cases hopefully doing something more
useful than a simple query of the table (e.g. replacing country codes with
the country, etc).  Anyway, point being that without either more
documentation or a client in between, it's not that easy for a user to know
what fields they can specify to a given endpoint anyhow, let alone how to
format them.  So meanwhile we can take care of fuzzy matching or case
irregularities in the client layer rather than worry about it at the API
level.  Make sense?

**Comment by sckott** [comment]
Sounds good. Actually, just tried querying in mysql locally here, and case doesn't seem to matter. Sorry, i thought it did matter :disappointed: 

spelling definitely matters, but yeah, i think we'd better just expect parameters to be spelled correctly and ignore if not for now

**Comment by sckott** [comment]
closed via 22729bd4a70ab632dc4456c10ba9c98728072bff
