### ISSUE TITLE
docker stats

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#29]
https://blog.logentries.com/2015/02/what-is-the-docker-stats-api/  wonder if stats on the containers is something to monitor

**Comment by cboettig** [comment]
yup, pretty sweet, though more for live diagnostics (like `top` for containers) than for logging purposes.

**Comment by sckott** [comment]
k, will be fun to play with, closing

**Comment by cboettig** [comment]
Just for fun, here's some sample stats on my server:

```
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
fbapi               0.00%               41.16 MiB/994 MiB   4.14%               2.945 MiB/781.2 KiB
fblogstash          0.59%               288.2 MiB/994 MiB   28.99%              25.82 KiB/6.33 KiB
fbmysql             0.05%               221.4 MiB/994 MiB   22.28%              91.57 KiB/2.576 MiB
fbnginx             0.00%               2.445 MiB/994 MiB   0.25%               0 B/0 B
fbredis             0.12%               1.625 MiB/994 MiB   0.16%               337.7 KiB/284.2 KiB
```

Note that because of the way I have `--net container:fbapi` on the fbnginx container, the NET I/O from ngninx is actually counted under `fbapi`.  

Note that logstash is the heaviest of the images, probably because of the kibana javascript, so it might be worth toggling that off if / when we're not using it.  (not sure how best to do that).  This is after a few queries have been made but otherwise not under heavy use.  Also the total memory usage might float higher than this if it could, but ~ 50% of memory has already been used in other tasks on my server.  Would be worth comparing this profile on a higher memory instance for comparison.

**Comment by sckott** [comment]
do you have a nice one liner to get those stats?  or `docker stats <containerid>` on each one?

**Comment by cboettig** [comment]
Not a _nice_ one-liner but:

```
docker stats $(docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\n" " ")
```

see https://github.com/docker/docker/issues/10772

**Comment by sckott** [comment]
:+1:
