### ISSUE TITLE
securing elasticsearch

### ISSUE THREAD

**Issue by sckott** [ropensci/fishbaseapi#43]
in case this applies to our api, some articles, etc. on securing elasticsearch:
- https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-on-an-ubuntu-vps
- https://www.digitalocean.com/community/tutorials/elasticsearch-fluentd-and-kibana-open-source-log-search-and-visualization
- http://saskia-vola.com/install-secure-elasticsearch-1-x-digital-ocean/
- http://stackoverflow.com/questions/26006373/how-to-secure-a-digital-ocean-elasticsearch-cluster

**Comment by cboettig** [comment]
Just some notes to myself here because I've wondered how the hell the seemingly standard setup of logstash+elasticsearch+kibana is ever secure.  

Looks like the standard thing here is to prevent elasticsearch from responding over the http client at all, such that it can only be used by applications running on the same host.  

e.g. [This digitalocean guide](https://www.digitalocean.com/community/tutorials/how-to-use-logstash-and-kibana-to-centralize-logs-on-centos-7) recommends the following configuration:

```
sudo vi /etc/elasticsearch/elasticsearch.yml
```

> Add the following line somewhere in the file, to disable dynamic scripts:

```
script.disable_dynamic: true
```

> You will also want to restrict outside access to your Elasticsearch instance, so outsiders can't read your data or shutdown your Elasticseach cluster through the HTTP API. Find the line that specifies network.host and uncomment it so it looks like this:

```
network.host: localhost
```

> Then disable multicast by finding the discovery.zen.ping.multicast.enabled item and uncommenting so it looks like this:

```
discovery.zen.ping.multicast.enabled: false
```

> Save and exit elasticsearch.yml.

I gather this would break access from the R client or anything running elsewhere, but might be the only way kibana can actually run on the localhost and access elasticsearch without elasticsearch being exposed and thus vulnerable.  At least that's my guess.

**Comment by sckott** [comment]
@cboettig thanks for the notes. So having worked with elasticsearch for a while, do you still want to stick with it?  Or too much of a pain?

**Comment by cboettig** [comment]
I think it's pretty cool, even though I haven't worked with the actual
query side of it.  Our current setup is solid.  I do think kibana is kinda
pointless so we may just ignore it.

**Comment by sckott** [comment]
right, i don't think we need kibana

**Comment by sckott** [comment]
The EL stack (elasticsearch, logstash)

**Comment by cboettig** [comment]
I think with https+a long password, and NGINX blocking any write requests, we're probably good here now.

**Comment by sckott** [comment]
@cboettig  agreed
