### ISSUE TITLE
config.yaml is no longer gitignored

### ISSUE THREAD

**Issue by MollsReis** [ropensci/fishbaseapi#81]
Wondering why you chose to remove `config.yaml` from `.gitignore`. The typically accepted pattern is to git ignore files with sensitive data or (in our case) data that may change from user to user.

**Comment by cboettig** [comment]
Right, but in our deploy method this is not sensitive data (mysql servers aren't publicly facing), nor would it be necessary to change these from user to user; `docker-compose up` should work just as well locally as when deploying on the server.  Does that make sense?  (I do realize you're probably a lot more experienced in this, so feel free to correct me -- but this does avoid manually recreating config.yaml as one moves the deployment from one host to another).

Of course the mysql containers are being run as stateless containers, linking local volumes for data storage, which obviously isn't portable.  I suppose there are solutions to that (flocker, or perhaps some of the more fully-fledged orchestration tools like Kubernetes or Mesos?) but that doesn't seem to be a big issue here.  Of course long-term we would hope to plug directly into the live SQL databases being used for fishbase and sealifebase, but meanwhile, this is relatively portable with minimal fuss / extra local user config.

**Comment by MollsReis** [comment]
Ultimately its your repo and your decision, but connection info typically is not stored as part of the code in the repository (regardless of sensitivity) as a practice. The `config_template.yaml` is provided so a user can quickly and easily create their own `config.yaml` without changing the source (according to git).

For instance, my connection info is different than yours. I can update `config.yaml` but git will try to track my changes since it is not ignored. As it stands now the code is less portable.

**Comment by cboettig** [comment]
Right, the current approach isn't compatible with quick deployment for cases like yours where you already have running mysql instances, which you very sensibly consider as something external. 

 But your connection information would not be different if you were content to just use the dockerized mysql containers and launch the thing with `docker-compose`.  As we've been testing on a few different servers, it has been convenient to just drop on a vanilla machine and run `import.sh` and `docker-compose up` rather than setting up custom mysql servers and custom config by hand each time.  

Once we are integrating more tightly with the real fishbase mysql servers, I completely agree that we drop out this hardwired `config.yaml` and the mysql docker containers, since they'd be redundant.  But for now, it's portable with less config provided you consider the sql instances as something that is also being moved around instead of being localized to each user.  This scales nicely to cluster instances too (though yes, local volume linking is still a bit of an open question for docker I believe).

**Comment by MollsReis** [comment]
Works for me :smile:
